# Generated by Django 5.2.9 on 2026-01-17 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_requests', '0005_alter_bloodrequest_assigned_donor'),
        ('register_donor', '0004_donor_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200)),
                ('blood_type', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], max_length=20)),
                ('next_donation_date', models.DateField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_donor.donor')),
            ],
        ),
        migrations.CreateModel(
            name='DonationConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_confirmed', models.BooleanField(default=False)),
                ('donor_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_donor.donor')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blood_requests.bloodrequest')),
            ],
        ),
    ]
