# Generated by Django 5.2.9 on 2026-01-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register_donor', '0004_donor_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('is_urgent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200)),
                ('blood_type', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_donor.donor')),
            ],
        ),
        migrations.CreateModel(
            name='CampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_donor.donor')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donationcamp')),
            ],
        ),
    ]
