# Generated by Django 5.2.9 on 2026-01-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0005_alter_bloodrequest_assigned_donor'),
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationconfirmation',
            name='donation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donationconfirmation',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_requests.bloodrequest'),
        ),
    ]
