# Generated by Django 5.2.9 on 2026-01-31 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donationconfirmation_confirmation_code'),
        ('register_donor', '0006_remove_donor_patient_donor_accepted_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationconfirmation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register_donor.donor'),
        ),
    ]
