# Generated by Django 5.2.9 on 2026-02-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_donationconfirmation_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='hospital',
        ),
    ]
