# Generated by Django 5.2.9 on 2026-02-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_remove_donation_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='hospital',
            field=models.CharField(default='Unknown Hospital', max_length=200),
            preserve_default=False,
        ),
    ]
