# Generated by Django 6.0.4 on 2026-04-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_donation_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='certificates/')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_count', models.IntegerField(default=0)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='donor.donation')),
            ],
        ),
    ]
