# Generated by Django 5.2.9 on 2026-01-30 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospitalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_request', to='hospital.hospital'),
        ),
    ]
