# Generated by Django 5.2.9 on 2026-02-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospitalprofile_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('hospital_type', models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('teaching', 'Teaching'), ('community', 'Community'), ('specialty', 'Specialty'), ('clinic', 'Clinic')], max_length=20, null=True)),
                ('bed_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_bank_type', models.CharField(blank=True, choices=[('storage_only', 'Storage Only'), ('collection_storage', 'Collection & Storage'), ('full_service', 'Full Service Blood Bank'), ('none', 'No Blood Bank Facility')], max_length=30)),
                ('contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('has_emergency', models.BooleanField(default=False)),
                ('has_icu', models.BooleanField(default=False)),
                ('has_operation_theater', models.BooleanField(default=False)),
                ('has_blood_storage', models.BooleanField(default=False)),
                ('has_blood_testing', models.BooleanField(default=False)),
                ('hosts_donation_camp', models.BooleanField(default=False)),
                ('registration_certificate', models.FileField(upload_to='hospital_docs/registration/')),
                ('medical_license', models.FileField(upload_to='hospital_docs/medical_license/')),
                ('blood_bank_license', models.FileField(blank=True, null=True, upload_to='hospital_docs/blood_bank/')),
                ('id_proof', models.FileField(upload_to='hospital_docs/id_proof/')),
                ('authority_letter', models.FileField(blank=True, null=True, upload_to='hospital_docs/authority_letter/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='bed_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='blood_bank_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='hospital_type',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='hospital.hospital'),
        ),
    ]
