# Generated by Django 5.2.9 on 2026-02-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospitalapplication_hospitalprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='hospital_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
