# Generated by Django 5.2.9 on 2026-03-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0009_rename_hospital_bloodrequest_hospital_location_and_more'),
        ('hospital', '0005_alter_hospitalprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_requests.hospitallocation'),
        ),
    ]
