# Generated by Django 5.2.9 on 2026-03-06 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_hospital_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Hospital Login'), ('blood_request_create', 'Blood Request Created'), ('stock_add', 'Blood Stock Added'), ('stock_remove', 'Blood Stock Removed'), ('inventory_update', 'Inventory Updated'), ('document_upload', 'Document Uploaded')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
