# Generated by Django 5.2.9 on 2026-03-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospitalauditlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalAuditLog',
        ),
    ]
