# Generated by Django 6.0.4 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_hospital_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalapplication',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
