# Generated by Django 5.2.9 on 2025-12-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
