# Generated by Django 5.2.9 on 2025-12-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_donor', '0002_donor_is_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='password',
        ),
    ]
