# Generated by Django 5.2.9 on 2026-01-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_donor', '0003_remove_donor_confirm_password_remove_donor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
