# Generated by Django 5.2.9 on 2026-01-31 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0009_delete_donor'),
        ('register_donor', '0004_donor_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='accepted_terms',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='consent_notifications',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='has_diabetes',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='has_heart_disease',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='has_hypertension',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='no_medical_conditions',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='state',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='donor',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to='loginsignup.patient'),
        ),
    ]
