# Generated by Django 5.2.9 on 2026-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_donor', '0005_remove_donor_accepted_terms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='patient',
        ),
        migrations.AddField(
            model_name='donor',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='consent_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='has_diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='has_heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='has_hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='no_medical_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
