# Generated by Django 5.2.9 on 2026-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_donor', '0006_remove_donor_patient_donor_accepted_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
