# Generated by Django 6.0.4 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_donor', '0008_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
