# Generated by Django 5.2.7 on 2025-11-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0002_remove_patient_confirm_password_patient_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emailaddress', models.EmailField(max_length=254, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
