# Generated by Django 5.2.7 on 2025-12-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0003_googlesignup_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emailaddress', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=15, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='googlesignup',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='googlesignup',
            old_name='emailaddress',
            new_name='email',
        ),
        migrations.AddField(
            model_name='googlesignup',
            name='credential',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='googlesignup',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('donor', 'Donor'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='googlesignup',
            name='fullname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='googlesignup',
            name='verification_code',
            field=models.CharField(max_length=6),
        ),
    ]
