# Generated by Django 5.2.9 on 2025-12-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0004_patient_rename_created_at_googlesignup_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('blood_type', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('weight', models.PositiveIntegerField(help_text='Weight in kg')),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('has_heart_disease', models.BooleanField(default=False)),
                ('no_medical_conditions', models.BooleanField(default=False)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('consent_notifications', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
