# Generated by Django 5.2.9 on 2025-12-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0005_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='citizenship_id',
            field=models.FileField(blank=True, null=True, upload_to='citizenships/'),
        ),
        migrations.AddField(
            model_name='donor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='donor_photos/'),
        ),
    ]
