# Generated by Django 5.2.9 on 2026-01-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0008_remove_donor_accepted_terms_remove_donor_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
