# Generated by Django 6.0.4 on 2026-04-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0009_delete_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlesignup',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='googlesignup',
            name='credential',
        ),
        migrations.AddField(
            model_name='googlesignup',
            name='pending_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='googlesignup',
            name='fullname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='googlesignup',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
