# Generated by Django 5.2.9 on 2026-02-04 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_stock', '0001_initial'),
        ('hospital', '0005_alter_hospitalprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodstock',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_stock', to='hospital.hospital'),
        ),
    ]
