# Generated by Django 5.2.9 on 2026-02-04 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_stock', '0002_alter_bloodstock_hospital'),
        ('hospital', '0005_alter_hospitalprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=3)),
                ('transaction_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=6)),
                ('units', models.PositiveIntegerField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_by', models.CharField(default='Hospital', max_length=100)),
                ('new_balance', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
