# Generated by Django 5.2.9 on 2026-03-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_stock', '0003_bloodstockhistory'),
        ('hospital', '0008_delete_hospitalauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstockhistory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodstockhistory',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='bloodstockhistory',
            name='performed_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
