# Generated by Django 5.2.9 on 2026-03-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_hospitalauditlog'),
        ('hospital', '0008_delete_hospitalauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('blood_request', 'Blood Request'), ('donor_registration', 'Donor Registration'), ('hospital_registration', 'Hospital Registration'), ('blood_request_approved', 'Blood Request Approved')], max_length=50),
        ),
    ]
