# Generated by Django 5.2.9 on 2026-03-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_notification_hospital_alter_notification_type'),
        ('hospital', '0008_delete_hospitalauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalauditlog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
