# Generated by Django 5.2.9 on 2026-03-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_hospitalauditlog_hospital'),
        ('blood_requests', '0012_bloodrequest_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_requests.bloodrequest'),
        ),
    ]
