# Generated by Django 5.2.9 on 2026-03-16 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_notification_blood_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('blood_request', 'Blood Request'), ('donor_registration', 'Donor Registration'), ('hospital_registration', 'Hospital Registration'), ('blood_request_approved', 'Blood Request Approved'), ('donor_request', 'Donor Request'), ('donor_accept', 'Donor Accepted')], max_length=50),
        ),
    ]
