# Generated by Django 5.2.9 on 2026-03-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_notification_user_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcamp',
            name='filled_slots',
        ),
        migrations.RemoveField(
            model_name='donationcamp',
            name='total_slots',
        ),
    ]
