# Generated by Django 5.2.9 on 2026-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_remove_donationcamp_filled_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcamp',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
