# Generated by Django 5.2.9 on 2026-03-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_donationcamp_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcamp',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
