# Generated by Django 5.2.9 on 2026-04-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_donationcamp_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcamp',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donationcamp',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
