# Generated by Django 5.2.9 on 2026-04-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_donationcamp_contact_number_donationcamp_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcamp',
            name='map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
