# Generated by Django 5.2.9 on 2026-04-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_alter_donationcamp_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('blood_request', 'Blood Request'), ('blood_request_approved_by_admin', 'Blood Request Approved by Admin'), ('donor_registration', 'Donor Registration'), ('hospital_registration', 'Hospital Registration'), ('blood_request_approved', 'Blood Request Approved'), ('donor_request', 'Donor Request'), ('donor_accept', 'Donor Accepted')], max_length=50),
        ),
    ]
