# Generated by Django 5.2.9 on 2026-04-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_notification_type'),
        ('blood_requests', '0015_alter_bloodrequest_status'),
        ('hospital', '0008_delete_hospitalauditlog'),
        ('register_donor', '0008_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_1_started', models.DateTimeField(blank=True, null=True)),
                ('tier_1_completed', models.DateTimeField(blank=True, null=True)),
                ('tier_1_donor_count', models.IntegerField(default=0)),
                ('tier_2_started', models.DateTimeField(blank=True, null=True)),
                ('tier_2_completed', models.DateTimeField(blank=True, null=True)),
                ('tier_2_donor_count', models.IntegerField(default=0)),
                ('tier_3_started', models.DateTimeField(blank=True, null=True)),
                ('tier_3_completed', models.DateTimeField(blank=True, null=True)),
                ('tier_3_donor_count', models.IntegerField(default=0)),
                ('tier_4_started', models.DateTimeField(blank=True, null=True)),
                ('tier_4_completed', models.DateTimeField(blank=True, null=True)),
                ('tier_4_donor_count', models.IntegerField(default=0)),
                ('blood_bank_checked', models.DateTimeField(blank=True, null=True)),
                ('blood_bank_stock_found', models.BooleanField(default=False)),
                ('blood_bank_units', models.IntegerField(default=0)),
                ('hospital_stock_checked', models.DateTimeField(blank=True, null=True)),
                ('hospital_stock_found', models.BooleanField(default=False)),
                ('hospital_stock_details', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_donors_alerted', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('blood_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation', to='blood_requests.bloodrequest')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('tier_1', 'Tier 1 (0-5km)'), ('tier_2', 'Tier 2 (5-15km)'), ('tier_3', 'Tier 3 (15-30km)'), ('tier_4', 'Tier 4 (30km+)')], max_length=10)),
                ('distance_km', models.FloatField()),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='blood_requests.bloodrequest')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register_donor.donor')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
