# Generated by Django 6.0.4 on 2026-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcamp',
            name='authorization_letter',
            field=models.FileField(blank=True, help_text='Official authorization letter or permission document (PDF/JPG/PNG, max 5MB)', null=True, upload_to='camp_documents/'),
        ),
    ]
