# Generated by Django 6.0.4 on 2026-05-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_alter_notification_type_add_donation_eligibility_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('alert', 'Alert'), ('system_alert', 'System Alert'), ('camp', 'Camp'), ('blood_request', 'Blood Request'), ('blood_request_approved_by_admin', 'Blood Request Approved by Admin'), ('blood_request_rejected_by_admin', 'Blood Request Rejected by Admin'), ('blood_request_failed', 'Blood Request Failed'), ('blood_bank_found', 'Blood Bank Found'), ('follow_up_24h', '24h Follow-up'), ('donor_registration', 'Donor Registration'), ('hospital_registration', 'Hospital Registration'), ('blood_request_approved', 'Blood Request Approved'), ('donor_request', 'Donor Request'), ('donor_accept', 'Donor Accepted'), ('donor_request_rejected', 'Donor Declined'), ('request_completed', 'Request Completed'), ('donation_eligibility_reminder', 'Donation Eligibility Reminder'), ('day_before_request_confirm', 'Day-Before Request Confirmation')], max_length=50),
        ),
    ]
