# Generated by Django 6.0.4 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationcamp',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationcamp',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationcamp',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
