# Generated by Django 5.2.9 on 2026-01-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0003_bloodrequest_assigned_donor_bloodrequest_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
