# Generated by Django 5.2.9 on 2026-01-17 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0004_bloodrequest_patient_confirmed'),
        ('register_donor', '0004_donor_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='assigned_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_donor.donor'),
        ),
    ]
