# Generated by Django 5.2.9 on 2026-01-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0005_alter_bloodrequest_assigned_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='donation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
