# Generated by Django 5.2.9 on 2026-01-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0006_bloodrequest_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='assigned_donor',
        ),
    ]
