# Generated by Django 5.2.9 on 2026-03-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0008_hospitallocation_alter_bloodrequest_hospital'),
        ('hospital', '0005_alter_hospitalprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='hospital',
            new_name='hospital_location',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='created_by_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to='hospital.hospital'),
        ),
    ]
