# Generated by Django 5.2.9 on 2026-03-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0009_rename_hospital_bloodrequest_hospital_location_and_more'),
        ('loginsignup', '0009_delete_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginsignup.patient'),
        ),
    ]
