# Generated by Django 5.2.9 on 2026-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0010_alter_bloodrequest_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='doctor_note',
            field=models.FileField(blank=True, null=True, upload_to='doctor_notes/'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_doc',
            field=models.FileField(blank=True, null=True, upload_to='hospital_docs/'),
        ),
    ]
