# Generated by Django 5.2.9 on 2026-03-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0011_alter_bloodrequest_doctor_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
