# Generated by Django 5.2.9 on 2026-03-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0012_bloodrequest_patient_name'),
        ('register_donor', '0007_donor_latitude_donor_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='register_donor.donor'),
        ),
    ]
