# Generated by Django 5.2.9 on 2026-03-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0013_bloodrequest_accepted_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=10),
        ),
    ]
