# Generated by Django 5.2.9 on 2026-03-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0014_bloodrequest_is_escalated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('escalated', 'Escalated')], default='pending', max_length=10),
        ),
    ]
