# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_requests", "0015_alter_bloodrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]

