# Generated by Django 6.0.4 on 2026-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0016_bloodrequest_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='required_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
