# Generated by Django 6.0.4 on 2026-04-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0017_alter_bloodrequest_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='units_required',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
