# Generated by Django 6.0.4 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0018_alter_bloodrequest_units_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
