# Generated by Django 6.0.4 on 2026-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_requests', '0019_bloodrequest_rejection_reason_and_rejected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('escalated', 'Escalated'), ('no_match', 'No Match Found')], default='pending', max_length=10),
        ),
    ]
